[versions]

junit = "5.10.0"

[libraries]

# Plugins
gradle-spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version = "7.0.3" }

junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api" }
