[versions]

junit = "5.10.0"

[libraries]

# Plugins
gradle-test-logger = { module = "com.adarshr:gradle-test-logger-plugin", version = "3.2.0" }
gradle-spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version = "6.21.0" }

junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api" }
