import java.util.*

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("me.jmlab.interview.common-conventions")

    id("me.jmlab.interview.maven-repository-conventions")

    id("me.jmlab.interview.jvm-junit-test-conventions")

    java

    id("com.diffplug.spotless")
}

tasks.withType(Jar::class).configureEach {
    manifest {
        attributes(mapOf(
            "Implementation-Title" to project.name,
            "Implementation-Version" to project.version,
            "Build-Date" to Date(),
            "Created-By" to "Suh Junmin (sof.midnight@live.co.kr)"
        ))
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

spotless {
    java {
        importOrder()

        removeUnusedImports()

        palantirJavaFormat()

        formatAnnotations()
    }
}
