name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      kroki:
        image: yuzutech/kroki
        env:
          KROKI_DIAGRAMSNET_HOST: diagramsnet
        ports:
          - 8000:8000

      diagramsnet:
        image: yuzutech/kroki-diagramsnet:latest
        ports:
          - 8005:8005

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Export KROKI_URL env
        run: echo "ORG_GRADLE_PROJECT_KROKI_URL=http://localhost:8080" >> $GITHUB_ENV

      - name: Generate document
        run: ./gradlew :html:buildDocument

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: html/build/html

  deploy:
    runs-on: ubuntu-latest

    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
